### ISSUE TITLE
About the training time

### ISSUE THREAD

**Issue by liuyang-ict** [antoyang/TubeDETR#1]
How much V100 GPU-time when TubeDETR was trained on HC-STVG?

**Comment by antoyang** [comment]
20 epochs on HC-STVGv2 took about 7 hours on 16 V100 for the best configuration (stride 4 resolution 352).

**Comment by liuyang-ict** [comment]
Thanks a lot~~

**Comment by ZhengPeng7** [comment]
If fewer GPUs are used for training, like 2~8 V100, will the accuracy decrease?
By the way, are your V100 cards all 32GB? Thanks in advance.

**Comment by ZhengPeng7** [comment]
By the way again, I think the `preproc_hstvgv2.py` in `preproc` should be `preproc_hcstvgv2.py`? :)

**Comment by antoyang** [comment]
I haven't tried training with a lower number of V100 but I don't think this would decrease the results. All the V100 used in experiments are 32GB, but you can use 16GB V100 with a lower resolution and/or higher temporal stride. The name of the preproc_hstvgv2.py file indeed had a typo, thanks for catching this!
