### ISSUE TITLE
Broken demo

### ISSUE THREAD

**Issue by xxiMiaxx** [antoyang/TubeDETR#19]
Hello guys, 

Thank you for the amazing work!

just wanted to highlight that the demo or the link are broken http://stvg.paris.inria.fr/

Thank you!.

**Comment by antoyang** [comment]
Hey, I have just restarted it. I am not sure why it regularly crashes, but I do not have the bandwidth to investigate this now.

**Comment by xxiMiaxx** [comment]
great, thank you.
